spring:
  datasource:
    url: jdbc:h2:mem:test

server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://fly-postgresql-test-database.fly.dev:5432/postgres
    username: postgres
    password: {PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
